import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  fetchSchema,
  fetchTableDescriptions,
  generateTableDescriptions,
  setTableDescription,
  clearTableDescription,
  setColumnDescription,
  clearColumnDescription,
} from "../lib/api";
import { getColumnBadges } from "../lib/columnMetadata";
import { useToast } from "./Toast";

export default function DescribeModal({
  dbName,
  isOpen = true,
  isModal = true,
  tables: initialTables = null,
  schemaVersion = 0,
  onClose,
  onDescriptionsChanged,
}) {
  const showToast = useToast();
  const [tables, setTables] = useState(initialTables);
  const [activeDbName, setActiveDbName] = useState(dbName || "");
  const [descriptions, setDescriptions] = useState({});
  const [loading, setLoading] = useState(!initialTables);
  const [generating, setGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [error, setError] = useState(null);

  // Table editing state
  const [editingTable, setEditingTable] = useState(null);
  const [draftTableText, setDraftTableText] = useState("");
  const [savingTable, setSavingTable] = useState(null);

  // Column editing state: { table, column } or null
  const [editingColumn, setEditingColumn] = useState(null);
  const [draftColumnText, setDraftColumnText] = useState("");
  const [savingColumn, setSavingColumn] = useState(null);

  useEffect(() => {
    let cancelled = false;

    async function loadData() {
      setLoading(true);
      setError(null);
      try {
        let currentTables = initialTables;
        if (!currentTables) {
          const schemaData = await fetchSchema();
          if (cancelled) return;
          currentTables = schemaData.tables;
          if (schemaData.database) setActiveDbName(schemaData.database);
        }
        setTables(currentTables);

        const descData = await fetchTableDescriptions();
        if (cancelled) return;
        if (descData.database && !activeDbName) setActiveDbName(descData.database);
        const descMap = descData.descriptions || {};
        setDescriptions(descMap);

        // Only set hasAutoGenerated to true if non-custom (LLM generated) entries exist
        const hasLLMDesc = Object.values(descMap).some(
          (t) => (t.description && !t.is_custom) || Object.values(t.columns || {}).some((c) => c.description && !c.is_custom)
        );
        if (hasLLMDesc) {
          setHasAutoGenerated(true);
        }
        onDescriptionsChanged?.(descMap);
      } catch (err) {
        if (cancelled) return;
        setError(err.message || "Failed to load schema descriptions.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    if (isOpen) {
      loadData();
    }

    return () => {
      cancelled = true;
    };
  }, [isOpen, schemaVersion, initialTables]);

  async function handleGenerate() {
    setGenerating(true);
    setError(null);
    try {
      const data = await generateTableDescriptions(hasAutoGenerated);
      const newDescs = data.descriptions || {};
      setDescriptions(newDescs);
      const wasGenerated = hasAutoGenerated;
      setHasAutoGenerated(true);
      onDescriptionsChanged?.(newDescs);
      showToast?.(
        wasGenerated ? "Descriptions regenerated successfully." : "Descriptions generated successfully.",
        "success"
      );
    } catch (err) {
      setError(err.message || "Could not generate descriptions.");
      showToast?.(err.message || "Could not generate descriptions.", "error");
    } finally {
      setGenerating(false);
    }
  }

  // --- Table Description Handlers ---
  function startEditingTable(tableName) {
    setEditingTable(tableName);
    setDraftTableText(descriptions[tableName]?.description || "");
  }

  function cancelEditingTable() {
    setEditingTable(null);
    setDraftTableText("");
  }

  async function saveEditingTable(tableName) {
    const trimmed = draftTableText.trim();
    if (!trimmed) {
      handleClearTable(tableName);
      return;
    }
    setSavingTable(tableName);
    try {
      const data = await setTableDescription(tableName, trimmed);
      const newDescs = data.descriptions || {};
      setDescriptions(newDescs);
      onDescriptionsChanged?.(newDescs);
      setEditingTable(null);
    } catch (err) {
      showToast?.(err.message || "Could not save description.", "error");
    } finally {
      setSavingTable(null);
    }
  }

  async function handleClearTable(tableName) {
    setSavingTable(tableName);
    try {
      const data = await clearTableDescription(tableName);
      const newDescs = data.descriptions || {};
      setDescriptions(newDescs);
      onDescriptionsChanged?.(newDescs);
      setEditingTable(null);
    } catch (err) {
      showToast?.(err.message || "Could not clear description.", "error");
    } finally {
      setSavingTable(null);
    }
  }

  // --- Column Description Handlers ---
  function startEditingColumn(tableName, columnName) {
    setEditingColumn({ table: tableName, column: columnName });
    const colDesc = descriptions[tableName]?.columns?.[columnName]?.description || "";
    setDraftColumnText(colDesc);
  }

  function cancelEditingColumn() {
    setEditingColumn(null);
    setDraftColumnText("");
  }

  async function saveEditingColumn(tableName, columnName) {
    const trimmed = draftColumnText.trim();
    if (!trimmed) {
      handleClearColumn(tableName, columnName);
      return;
    }
    setSavingColumn(`${tableName}.${columnName}`);
    try {
      const data = await setColumnDescription(tableName, columnName, trimmed);
      const newDescs = data.descriptions || {};
      setDescriptions(newDescs);
      onDescriptionsChanged?.(newDescs);
      setEditingColumn(null);
    } catch (err) {
      showToast?.(err.message || "Could not save column description.", "error");
    } finally {
      setSavingColumn(null);
    }
  }

  async function handleClearColumn(tableName, columnName) {
    setSavingColumn(`${tableName}.${columnName}`);
    try {
      const data = await clearColumnDescription(tableName, columnName);
      const newDescs = data.descriptions || {};
      setDescriptions(newDescs);
      onDescriptionsChanged?.(newDescs);
      setEditingColumn(null);
    } catch (err) {
      showToast?.(err.message || "Could not clear column description.", "error");
    } finally {
      setSavingColumn(null);
    }
  }

  if (!isOpen && isModal) return null;

  const content = (
    <div
      className={`relative w-full ${
        isModal ? "max-w-[720px] max-h-[85vh] my-auto shadow-2xl" : "max-w-full"
      } bg-[#FFFDF9] dark:bg-[#181715] rounded-2xl border border-[#EDE5D8] dark:border-stone-800 flex flex-col overflow-hidden text-[#23201C] dark:text-stone-100 font-sans transition-all`}
    >
      {/* Header */}
      <div className="p-6 pb-4 border-b border-[#F4EDE2] dark:border-stone-800/80 flex items-start justify-between gap-4">
        <div>
          <h2 id="modal-title" className="font-mono text-2xl font-bold text-[#23201C] dark:text-stone-100 tracking-tight">
            {isModal
              ? `Describe ${activeDbName || dbName || "Database"}`
              : "TABLE & COLUMN DESCRIPTIONS"}
          </h2>
          <p className="text-sm text-[#787163] dark:text-stone-400 mt-2 max-w-[540px] leading-relaxed">
            {isModal
              ? hasAutoGenerated
                ? "We've generated descriptions for your database tables. You can edit them if you'd like, or continue."
                : 'Not everyone looking at this schema will know what an ambiguous column like "status" actually means — a short note here fixes that for good, and helps the SQL model too. Write these by hand or generate them below.'
              : 'Sent to the SQL-generation model as context — an accurate description here is what turns an ambiguous column like "status" into correct SQL instead of a guess.'}
          </p>
        </div>

        <div className="flex items-center gap-3 shrink-0">
          <button
            onClick={handleGenerate}
            disabled={generating || loading}
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-semibold bg-[#FFFDF9] dark:bg-[#25221E] hover:bg-[#FAF3E5] dark:hover:bg-[#302B25] text-[#B86B12] dark:text-amber-400 border border-[#E6D7BD] dark:border-amber-900/40 shadow-xs transition-all active:scale-[0.98] disabled:opacity-60 cursor-pointer"
          >
            {generating ? (
              <>
                <span className="w-3.5 h-3.5 border-2 border-amber-600/40 border-t-amber-600 rounded-full animate-spin" />
                <span>{hasAutoGenerated ? "Regenerating…" : "Generating…"}</span>
              </>
            ) : (
              <>
                <span>✨</span>
                <span>{hasAutoGenerated ? "Regenerate descriptions" : "Generate descriptions"}</span>
              </>
            )}
          </button>

          {isModal && (
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-stone-400 hover:text-stone-600 dark:hover:text-stone-200 hover:bg-stone-100 dark:hover:bg-stone-800 transition cursor-pointer"
              aria-label="Close"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          )}
        </div>
      </div>

      {/* Body: Table Cards List */}
      <div className="flex-1 overflow-y-auto p-6 space-y-4 max-h-[560px] min-h-[220px]">
        {error && (
          <div className="p-3 text-xs text-red-700 bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-900/40 rounded-xl">
            {error}
          </div>
        )}

        {loading && (
          <div className="space-y-4 py-4 px-2">
            <div className="flex items-center gap-3">
              <span className="w-4 h-4 border-2 border-amber-600/40 border-t-amber-600 rounded-full animate-spin shrink-0" />
              <span className="text-xs font-medium text-[#787163] dark:text-stone-400">
                Reading database schema…
              </span>
            </div>
            {[0, 1, 2].map((i) => (
              <div
                key={i}
                className="space-y-2.5 p-5 rounded-2xl bg-[#FAF7F2] dark:bg-[#1E1C19] border border-[#EEE5D6] dark:border-stone-800 animate-pulse"
              >
                <div className="h-4 bg-stone-200 dark:bg-stone-800 rounded w-1/4 mb-3" />
                <div className="h-3 bg-stone-200 dark:bg-stone-800 rounded w-2/3" />
                <div className="h-3 bg-stone-200 dark:bg-stone-800 rounded w-1/2" />
              </div>
            ))}
          </div>
        )}

        {!loading && tables && tables.length === 0 && (
          <p className="text-sm text-stone-500 italic py-6 text-center">
            No tables found in active database schema.
          </p>
        )}

        {!loading &&
          tables &&
          tables.map((table) => {
            const tableEntry = descriptions[table.name];
            const isEditingTbl = editingTable === table.name;
            const isSavingTbl = savingTable === table.name;
            const colDescs = tableEntry?.columns || {};

            return (
              <div
                key={table.name}
                className="bg-[#FAF7F2] dark:bg-[#1E1C19] border border-[#EEE5D6] dark:border-stone-800/90 rounded-2xl p-5 shadow-xs transition-colors"
              >
                {/* Table Header */}
                <div className="flex items-center gap-2">
                  <span className="font-mono text-sm text-[#A89F90] dark:text-stone-500">⊞</span>
                  <span className="font-mono text-base font-bold text-[#23201C] dark:text-stone-100">
                    {table.name}
                  </span>
                </div>

                {/* Table Description / Add Description */}
                <div className="mt-1.5 ml-6">
                  {isEditingTbl ? (
                    <div className="mt-1 flex items-center gap-2">
                      <input
                        type="text"
                        autoFocus
                        value={draftTableText}
                        onChange={(e) => setDraftTableText(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === "Enter") saveEditingTable(table.name);
                          if (e.key === "Escape") cancelEditingTable();
                        }}
                        onBlur={() => saveEditingTable(table.name)}
                        className="text-xs font-sans rounded-lg border border-[#9E9686] dark:border-stone-600 bg-white dark:bg-[#141312] px-3 py-1.5 text-[#23201C] dark:text-stone-100 focus:outline-none focus:ring-1 focus:ring-amber-600 shadow-inner w-full max-w-[500px]"
                        placeholder={`Description for ${table.name}`}
                      />
                      {isSavingTbl && <span className="text-xs text-stone-400">Saving…</span>}
                    </div>
                  ) : tableEntry?.description ? (
                    <span
                      onClick={() => startEditingTable(table.name)}
                      className="cursor-pointer text-xs text-[#5C5547] dark:text-stone-300 font-sans hover:bg-stone-200/60 dark:hover:bg-stone-800/60 px-1 py-0.5 rounded transition"
                      title="Click to edit table description"
                    >
                      {tableEntry.description}
                    </span>
                  ) : (
                    <button
                      onClick={() => startEditingTable(table.name)}
                      className="text-xs font-sans font-medium text-[#9E9584] hover:text-[#5E5647] dark:hover:text-stone-300 transition flex items-center gap-1 cursor-pointer"
                    >
                      + Add description
                    </button>
                  )}
                </div>

                <hr className="border-t border-[#EEE5D6] dark:border-stone-800/80 my-3.5" />

                {/* Column List */}
                <div className="space-y-3 ml-6">
                  {table.columns &&
                    table.columns.map((col) => {
                      const isEditingCol =
                        editingColumn?.table === table.name && editingColumn?.column === col.name;
                      const isSavingCol = savingColumn === `${table.name}.${col.name}`;
                      const colDescEntry = colDescs[col.name];
                      const colDesc = colDescEntry?.description;

                      // Automatically detect Primary Key & References badges
                      // "deleting the referenced table must remove this referencing icon automatically"
                      const badges = getColumnBadges(table, col, tables);

                      return (
                        <div
                          key={col.name}
                          className="flex flex-wrap items-center gap-x-2 gap-y-1.5 text-xs font-mono"
                        >
                          {/* Column Name */}
                          <span className="font-bold text-[#23201C] dark:text-stone-200">
                            {col.name}:
                          </span>

                          {/* Column Description / Add description */}
                          {isEditingCol ? (
                            <div className="inline-flex items-center gap-2">
                              <input
                                type="text"
                                autoFocus
                                value={draftColumnText}
                                onChange={(e) => setDraftColumnText(e.target.value)}
                                onKeyDown={(e) => {
                                  if (e.key === "Enter") saveEditingColumn(table.name, col.name);
                                  if (e.key === "Escape") cancelEditingColumn();
                                }}
                                onBlur={() => saveEditingColumn(table.name, col.name)}
                                className="text-xs font-sans rounded-lg border border-[#9E9686] dark:border-stone-600 bg-white dark:bg-[#141312] px-3 py-1 text-[#23201C] dark:text-stone-100 focus:outline-none focus:ring-1 focus:ring-amber-600 shadow-inner min-w-[260px] max-w-[400px]"
                                placeholder={`Description for ${col.name}`}
                              />
                              {isSavingCol && <span className="text-[11px] text-stone-400">Saving…</span>}
                            </div>
                          ) : colDesc ? (
                            <span
                              onClick={() => startEditingColumn(table.name, col.name)}
                              className="font-sans text-xs text-[#5C5547] dark:text-stone-300 hover:bg-stone-200/60 dark:hover:bg-stone-800/60 px-1 py-0.5 rounded cursor-pointer transition"
                              title="Click to edit column description"
                            >
                              {colDesc}
                            </span>
                          ) : (
                            <button
                              onClick={() => startEditingColumn(table.name, col.name)}
                              className="font-sans text-xs font-medium text-[#9E9584] hover:text-[#5E5647] dark:hover:text-stone-300 transition cursor-pointer"
                            >
                              + Add description
                            </button>
                          )}

                          {/* Column Badges (🔑 Primary Key, 🔗 References ONLY) */}
                          {badges.map((b, idx) => {
                            if (b.type === "primary_key") {
                              return (
                                <span
                                  key={idx}
                                  className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-mono bg-[#FAF0D7] dark:bg-[#332813] text-[#8C6212] dark:text-[#F3D382] border border-[#F3E2B8] dark:border-[#52401B] font-medium ml-1 shrink-0 select-none"
                                >
                                  <span>🔑</span>
                                  <span>{b.label}</span>
                                </span>
                              );
                            }
                            if (b.type === "reference") {
                              return (
                                <span
                                  key={idx}
                                  className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-mono bg-[#EEE9DF] dark:bg-[#2A2723] text-[#5E574B] dark:text-[#D1C9BC] border border-[#E2DAD0] dark:border-stone-700 font-medium ml-1 shrink-0 select-none"
                                >
                                  <span>🔗</span>
                                  <span>{b.label}</span>
                                </span>
                              );
                            }
                            return null;
                          })}
                        </div>
                      );
                    })}
                </div>
              </div>
            );
          })}
      </div>

      {/* Footer (Modal Mode only) */}
      {isModal && (
        <div className="p-5 border-t border-[#F4EDE2] dark:border-stone-800 flex items-center justify-between gap-4 bg-[#FFFDF9] dark:bg-[#181715]">
          <p className="text-xs text-[#847C6C] dark:text-stone-400 font-medium max-w-[480px]">
            Everything here is saved as you go — find this again anytime on the Schema tab, below the diagram.
          </p>

          <button
            onClick={onClose}
            disabled={loading || generating}
            className="px-6 py-2.5 bg-[#44574A] hover:bg-[#38483D] active:scale-[0.98] disabled:opacity-50 text-white text-sm font-semibold rounded-xl shadow-xs transition-all cursor-pointer"
          >
            {hasAutoGenerated ? "Continue" : "Done"}
          </button>
        </div>
      )}
    </div>
  );

  if (!isModal) {
    return content;
  }

  return (
    <AnimatePresence>
      {isOpen && (
        <div
          role="dialog"
          aria-modal="true"
          aria-labelledby="modal-title"
          className="fixed inset-0 z-50 bg-black/40 backdrop-blur-[2px] flex items-center justify-center p-4 sm:p-6 overflow-y-auto"
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.97, y: 6 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.97, y: 6 }}
            transition={{ duration: 0.2 }}
            className="w-full flex justify-center"
          >
            {content}
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
