import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import DescribeModal from "../DescribeModal";
import { ToastProvider } from "../Toast";

// The previous version of this test file never imported DescribeModal at
// all — it copy-pasted the hasAutoGenerated expression from inside the
// component and tested that copy in isolation. That can't catch a
// regression in the real component (and didn't: the overwrite_custom
// bug shipped anyway). Every test below renders the actual component
// and only mocks the network boundary (../lib/api).
vi.mock("../../lib/api", () => ({
  fetchSchema: vi.fn(),
  fetchTableDescriptions: vi.fn(),
  generateTableDescriptions: vi.fn(),
  setTableDescription: vi.fn(),
  clearTableDescription: vi.fn(),
  setColumnDescription: vi.fn(),
  clearColumnDescription: vi.fn(),
}));

import {
  fetchSchema, fetchTableDescriptions, generateTableDescriptions,
  setTableDescription,
} from "../../lib/api";

const TABLES = [
  {
    name: "orders",
    columns: [
      { name: "order_id", type: "INTEGER", pk: true },
      { name: "customer_id", type: "INTEGER" },
      { name: "status", type: "TEXT" },
    ],
    foreign_keys: [{ column: "customer_id", references_table: "customers", references_column: "customer_id" }],
  },
  {
    name: "customers",
    columns: [{ name: "customer_id", type: "INTEGER", pk: true }, { name: "name", type: "TEXT" }],
    foreign_keys: [],
  },
];

function renderModal(props = {}) {
  return render(
    <ToastProvider>
      <DescribeModal dbName="RetailDB" tables={TABLES} isModal={false} {...props} />
    </ToastProvider>
  );
}

beforeEach(() => {
  vi.clearAllMocks();
  fetchSchema.mockResolvedValue({ database: "RetailDB", tables: TABLES });
});

describe("DescribeModal — generate button behavior", () => {
  it('shows "Generate descriptions" (not "Regenerate") when nothing has been described yet', async () => {
    fetchTableDescriptions.mockResolvedValue({ database: "RetailDB", descriptions: {} });
    renderModal();

    expect(await screen.findByText("Generate descriptions")).toBeInTheDocument();
  });

  it('shows "Regenerate descriptions" once an auto-generated description already exists', async () => {
    fetchTableDescriptions.mockResolvedValue({
      database: "RetailDB",
      descriptions: { orders: { description: "Order records.", is_custom: false, columns: {} } },
    });
    renderModal();

    expect(await screen.findByText("Regenerate descriptions")).toBeInTheDocument();
  });

  it(
    "REGRESSION: a schema with ONLY a manual (custom) description still shows " +
    '"Generate descriptions", not "Regenerate" — proving hasAutoGenerated is not ' +
    "conflated with 'any description exists'",
    async () => {
      // This is exactly the bug: hasGenerated used to become true the
      // moment ANY description existed, including a hand-typed one —
      // so the very first real "Generate" click would pass
      // overwrite_custom=true and could wipe the manual edit that
      // triggered the flag in the first place.
      fetchTableDescriptions.mockResolvedValue({
        database: "RetailDB",
        descriptions: { orders: { description: "My own manual note.", is_custom: true, columns: {} } },
      });
      renderModal();

      expect(await screen.findByText("Generate descriptions")).toBeInTheDocument();
      expect(screen.queryByText("Regenerate descriptions")).not.toBeInTheDocument();
    }
  );

  it(
    "clicking Generate for the first time (manual description only) calls the API " +
    "with overwriteCustom=false, so the manual edit cannot be wiped",
    async () => {
      fetchTableDescriptions.mockResolvedValue({
        database: "RetailDB",
        descriptions: { orders: { description: "My own manual note.", is_custom: true, columns: {} } },
      });
      generateTableDescriptions.mockResolvedValue({ descriptions: {} });
      const user = userEvent.setup();
      renderModal();

      const button = await screen.findByText("Generate descriptions");
      await user.click(button);

      await waitFor(() => expect(generateTableDescriptions).toHaveBeenCalledWith(false));
    }
  );

  it(
    "clicking Regenerate after a real auto-generation calls the API with overwriteCustom=true",
    async () => {
      fetchTableDescriptions.mockResolvedValue({
        database: "RetailDB",
        descriptions: { orders: { description: "Auto-generated.", is_custom: false, columns: {} } },
      });
      generateTableDescriptions.mockResolvedValue({ descriptions: {} });
      const user = userEvent.setup();
      renderModal();

      const button = await screen.findByText("Regenerate descriptions");
      await user.click(button);

      await waitFor(() => expect(generateTableDescriptions).toHaveBeenCalledWith(true));
    }
  );

  it("switches to Regenerate wording immediately after a first successful generation", async () => {
    fetchTableDescriptions.mockResolvedValue({ database: "RetailDB", descriptions: {} });
    generateTableDescriptions.mockResolvedValue({
      descriptions: { orders: { description: "Order records.", is_custom: false, columns: {} } },
    });
    const user = userEvent.setup();
    renderModal();

    const button = await screen.findByText("Generate descriptions");
    await user.click(button);

    expect(await screen.findByText("Regenerate descriptions")).toBeInTheDocument();
  });
});

describe("DescribeModal — real FK-derived badges", () => {
  it("shows a References badge for a column with a real foreign key", async () => {
    fetchTableDescriptions.mockResolvedValue({ database: "RetailDB", descriptions: {} });
    renderModal();

    expect(await screen.findByText("References customers.customer_id")).toBeInTheDocument();
  });

  it("shows a Primary key badge for a real primary key column", async () => {
    fetchTableDescriptions.mockResolvedValue({ database: "RetailDB", descriptions: {} });
    renderModal();

    const badges = await screen.findAllByText("Primary key");
    expect(badges.length).toBeGreaterThan(0);
  });
});

describe("DescribeModal — table description editing", () => {
  it("clicking + Add description on a table reveals an editable input", async () => {
    fetchTableDescriptions.mockResolvedValue({ database: "RetailDB", descriptions: {} });
    const user = userEvent.setup();
    renderModal();

    const addButtons = await screen.findAllByText("+ Add description");
    // The orders table is rendered first — its table-level add-description
    // button is the first one in document order.
    await user.click(addButtons[0]);

    expect(screen.getByPlaceholderText("Description for orders")).toBeInTheDocument();
  });

  it("typing a description and pressing Enter saves it via the API", async () => {
    fetchTableDescriptions.mockResolvedValue({ database: "RetailDB", descriptions: {} });
    setTableDescription.mockResolvedValue({
      descriptions: { orders: { description: "Customer purchase orders.", is_custom: true, columns: {} } },
    });
    const user = userEvent.setup();
    renderModal();

    const addButtons = await screen.findAllByText("+ Add description");
    await user.click(addButtons[0]);
    const input = screen.getByPlaceholderText("Description for orders");
    await user.type(input, "Customer purchase orders.{Enter}");

    await waitFor(() =>
      expect(setTableDescription).toHaveBeenCalledWith("orders", "Customer purchase orders.")
    );
  });
});

describe("DescribeModal — loading and error states", () => {
  it("shows an error message if fetching descriptions fails", async () => {
    fetchTableDescriptions.mockRejectedValue(new Error("Network error"));
    renderModal();

    expect(await screen.findByText("Network error")).toBeInTheDocument();
  });

  it("surfaces a generation failure without crashing", async () => {
    fetchTableDescriptions.mockResolvedValue({ database: "RetailDB", descriptions: {} });
    generateTableDescriptions.mockRejectedValue(new Error("GROQ_API_KEY is not set."));
    const user = userEvent.setup();
    renderModal();

    const button = await screen.findByText("Generate descriptions");
    await user.click(button);

    const matches = await screen.findAllByText("GROQ_API_KEY is not set.");
    expect(matches.length).toBeGreaterThan(0);
  });
});
